apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: 656725130383.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "passwors"
  imagePullSecrets:
    - name: regcred
